name: Patch Image via URL

on:
  workflow_dispatch:
    inputs:
      image_url:
        description: 'Recovery Image URL'
        default: 'https://transfer.sh/<file-id>/<file>.img'
        required: true
        type: string

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1

    - name: Install necessary packages
      run: |
         sudo apt update
         sudo apt install -y git wget lz4 tar openssl python3

    - name: Download recovery image
      run: |
         wget -O recovery.img ${{ github.event.inputs.image_url }}
         file recovery.img

    - name: Unpack LZ4 if needed
      run: |
         if file recovery.img | grep -qi lz4; then
           echo "Detected LZ4 compressed image, unpacking..."
           mv recovery.img recovery.img.lz4
           lz4 -d recovery.img.lz4 recovery.img
         fi

    - name: Patch recovery
      run: |
         chmod +x magiskboot patcher-minimal
         ./patcher-minimal

    - name: Generate Odin flashable .tar.md5
      run: |
         cd output
         tar cvf output.tar output.img
         md5sum output.tar > output.tar.md5
         ls -lh

    - name: Upload patched image files
      uses: actions/upload-artifact@v4
      with:
        path: output/*
        name: Patched Recovery Image Bundle
        if-no-files-found: error
        retention-days: 15
        compression-level: 0
        overwrite: true

    - name: Upload keys for patched image
      uses: actions/upload-artifact@v4
      with:
        path: keys/*
        name: Patched Image Key Bundle
        if-no-files-found: error
        retention-days: 15
        compression-level: 0
        overwrite: true

